title: "未経験文系卒女性駆け出しエンジニアの（およそ）20年史"
summary: "未経験文系卒女性駆け出しエンジニアの（およそ）20年史"
topics: ["初心者", "ポエム", "キャリア", "就活", "未経験"] # トピック（5つまで）
published: true # falseだと下書き
price: 200 # 有料の場合200〜5000
chapters:
  - my-20years-history-1 # チャプター1
  - my-20years-history-2 # チャプター2
