title: "未経験文系卒女性駆け出しエンジニアの（およそ）20年史"
summary: "娘・息子育児中。上海赴任と産育休を経て、発信活動を開始し2021デブサミウーマンと2022 デブサミ登壇。2021年のQiita年間 TOP Contributor2位。

リモートワークの時代、女性こそエンジニアになるべきでは？と考える。自身の経歴と失敗を振り返りながら、これから未経験文系卒女性でも、育児中でも、ブランクがあっても。

タイトルは未経験も文系も女性も関係ないよという意味。2003年4月新卒入社。テレビ、新聞、出版社を一通り受けたミーハーな文系大学生だった私はITベンチャーを就職活動中に志した。

研修でLANケーブルを自作させられた。社長秘書と少女マンガネタで語らう仲になり顔を覚えてもらう工夫をした。ところが2年目。仕事に飽きる。黙々熱心に開発者が開発に勤しんでいる部署に私は異動したい。勝手に机を移動して異動した。

怒られながらも、思い出深いプロジェクト。「社内で誰も手を出していない領域の唯一になる」という使命感の結果、大手顧客に通う。「私の作ったものが、いま、目の前で使われている」という現場。

思えば就職活動時代から自分が作ったものを届けて喜ばれたかった。なんだ、意外とこういうことなんだな、と叶った。そんな10年目、2013年6月、こんどは上海事業所に異動。

「しななそうだから」という理由での赴任。夢の海外生活だけではすまない。多くの人と話せた一方、中国で学んだことは家族、故郷。子どもは授かりものだと思う。

帰任。そして娘を連れながら出勤する新たな日々に変わる。子どもは簡単に調子を崩す。自分だけではどうにもならないことがあることを初めて知った。チームで仕事をしよう。明らかに「以前」と異なったやり方で働くことに。

2回の産育休後、果たして私は社会に何が恩返しできるでしょう。未経験でもエンジニア。私が就職した2003年、氷河期。そこから1.5ヵ月の切迫早産入院と出産を経て、相変わらずの職場に戻る。そんな20年の話です。"
topics: ["初心者", "ポエム", "キャリア", "就活", "未経験"] # トピック（5つまで）
published: true # falseだと下書き
price: 200 # 有料の場合200〜5000
chapters:
  - my-20years-history-1 # チャプター1
  - my-20years-history-2 # チャプター2
  - my-20years-history-3
  - my-20years-history-4
  - my-20years-history-4-1
